# Generated by Django 4.2.5 on 2023-09-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_manager_event_pymanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pymanager',
            new_name='manager',
        ),
    ]
