# Generated by Django 4.2.5 on 2023-09-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_description_alter_event_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='manager',
            new_name='pymanager',
        ),
    ]
